### ISSUE TITLE
Windows executable? 

### ISSUE THREAD

**Issue by dsisnero** [dry-rb/dry-files#15]
## Describe the bug

Trying Hanami 2.0 - when it is installing files with bundler.install!  from cli/commands/gem/new.rb line 57

cli/bundler.rb line 149-157 when searching for bundle command
`
def which(cmd)
     # Adapted from https://stackoverflow.com/a/5471032/498386
    ENV["PATH"].split(File::PATH_SEPARATOR).each do |path|
      exe = fs.join(path, cmd)
      return exe if fs.executable?(exe) && !fs.directory?(exe)
   end
  
   
end
`
on windows fs.executable? returns false even if the bundle command exists 

in dry/files/file_system.rb 340-345
`
def executable?(path)
   file.executable?(path)
 end

This causes the system_call in hanami/cli/bundler to be
`
"install --jobs=12 --quiet --no-color"
`
and not
`
"bundle install --jobs=12 --quiet --no-color"

Resulting in the following error
"ERROR: Access to the registry path is denied.\nERROR: Access to the registry path is denied.\n\\Microsoft was unexpected at this time."

## My environment

- Affects my production application: **YES/NO**
- Ruby version: ...ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]
- OS: Windows

**Comment by jodosha** [comment]
@dsisnero by https://github.com/hanami/cli/pull/72 should have fixed the problem.

The bugfix will be released with the next version of Hanami: 2.0.3.
